name = "wowsim-classic"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:pages"

[build.upload]
format = "service-worker"

[[redirects]]
from = "/classic/*"
to = "/classic/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/classic/"
status = 301 